apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: socket-server
  name: socket-server
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socket-server
  strategy: {}
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      containers:
      - image: registry.gitlab.com/innovate-tech/poc-work/cilium-socket-lb:931932d04f2e5d1150693cd01aa880bd1489b24d
        name: socket-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: socket-server
  annotations:
    service.cilium.io/lb-l7: enabled
    service.cilium.io/lb-l7-algorithm: round_robin
  name: socket-server
  namespace: devops
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: socket-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: socket-server
  name: socket-server
  namespace: devops
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:246613758532:certificate/799416e9-c55e-4288-8201-080eef184ef1
    alb.ingress.kubernetes.io/group.name: ap-shared-ingress
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/backend-protocol-version: "GRPC"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - host: cilium-socker-lb.advancedpedagogy.com
    http:
      paths:
      - backend:
          service:
            name: socket-server
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
